name: Next Build and Deploy CI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version Description for Logging
        default: Default Bump Version
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps: 
    - name: Logging message Bump
      run: |
        echo "Running with Message: $BUMP_MESSAGE"
      env: 
        BUMP_MESSAGE: ${{ inputs.version }}
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Setup pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 7.27.0
    - name: Setup Node 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build site with Next
      run: pnpm build
    - name: SSH Deploy & Restart PM2
      uses: easingthemes/ssh-deploy@v4.1.0
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: ${{secrets.PM2 Restart }}
    - name: Purge Cloudflare cache
      run: |
        curl --fail-with-body -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
        -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
